#!/bin/sh

# paksa LAN jadi static, bukan DHCP client
uci set network.lan=interface
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'

# bridge ke port tunggal HG680P
uci -q delete network.@device[0]
uci add network device >/dev/null
uci set network.@device[-1].name='br-lan'
uci set network.@device[-1].type='bridge'
uci add_list network.@device[-1].ports='eth0'

# DHCP server LAN tetap aktif
uci set dhcp.lan=dhcp
uci set dhcp.lan.interface='lan'
uci set dhcp.lan.start='100'
uci set dhcp.lan.limit='150'
uci set dhcp.lan.leasetime='12h'
uci delete dhcp.lan.ignore

uci commit network
uci commit dhcp
exit 0
